"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iz%ko0xt%^fsp0d255m3*!=fbo0r%cqi$8yi4niilgj0pv8)t*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

STATIC_URL = '/static/'
STATIC_ROOT = '/opt/task_managet/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition
AUTH_USER_MODEL = 'tasks.CustomUser'  # Добавь эту строку
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'rest_framework',
    'auth_api',
    'corsheaders',
    'releases',
    'mozilla_django_oidc',
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tasks.auth_backends.AuthentikOIDCBackend',  # Путь к твоему файлу с бэкендом
    'django.contrib.auth.backends.ModelBackend', # Оставь для локальных админов/superuser
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/opt/task_manager/data/db.sqlite3',  # Новая папка
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MAX_UPLOAD_SIZE = 4 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE


OIDC_RP_CLIENT_ID = 'ZjxcInz9MKhMXV757Zn6Sq0W1E0D1OIaHw853UEt'  # ⚠️ ВАЖНО: Создай НОВОЕ приложение в Authentik для этого проекта!
OIDC_RP_CLIENT_SECRET = '4RUuBJ3TERKCZjg2A87w8TbWPQqyXAc4KaWSETk3LAXeLSP3xv7uGW36FIvaAXDw92hmKFuGQdfGMrFF5nW6pUrkZyJ83HofnqlDU6B5L8TCmuHwIwmiaYAzdLKDxkXU'

OIDC_OP_AUTHORIZATION_ENDPOINT = "https://ldap.cyndykshop.ru/application/o/authorize/"
OIDC_OP_TOKEN_ENDPOINT = "https://ldap.cyndykshop.ru/application/o/token/"
OIDC_OP_USER_ENDPOINT = "https://ldap.cyndykshop.ru/application/o/userinfo/"
OIDC_OP_JWKS_ENDPOINT = "https://ldap.cyndykshop.ru/application/o/apanel/jwks/" # Проверь путь, обычно /application/o/<provider>/jwks/

OIDC_RP_SIGN_ALGO = "RS256"
OIDC_CREATE_USER = True

LOGIN_REDIRECT_URL = '/' 
LOGOUT_REDIRECT_URL = '/login/'

# Опционально: если хочешь, чтобы logout разлогинивал и в Authentik тоже
OIDC_OP_LOGOUT_URL_METHOD = 'tasks.auth_backends.logout_redirect' # См. ниже