# Generated by Django 5.2.5 on 2025-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_customuser_avatar_customuser_telegram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(default='🔗', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма к оплате'),
        ),
    ]
